name: Deploy to WSL - Hello DevOps

on:
  push:
    branches: [ "master" ]   # match your repo branch

jobs:
  deploy:
    runs-on: self-hosted     # use your local runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run deployment script
      run: |
        cd ~/hello-devops
        git pull || true
        ./run.sh
          ./run.sh

